version: '3.7'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    command: npm run start:dev
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - '.:/usr/src/app'
    ports:
      - 3000:3000
    depends_on:
      - prisma-db
    env_file:
      - .env

  prisma-db:
    container_name: prisma-db
    image: postgres:12
    ports:
      - "5403:5432"
    volumes:
      - prisma-store:/var/lib/postgresql/data
    env_file:
      - .env

  prisma-test-db:
    container_name: prisma-test-db
    image: postgres:12
    ports:
      - "5402:5432"
    volumes:
      - prisma-test-store:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  prisma-store:
    driver: local
  prisma-test-store:
    driver: local
