@startuml
rectangle チーム集約 {
  Object チーム {
    チーム名
    所属ペア
  }
  Object ペア {
    ペア名
    所属参加者
  }
}


rectangle 参加者集約 {
Object 参加者 {
    名前
    メールアドレス
    在籍ステータス
  }
  Object 在籍ステータス {
    ステータス名
  }
}

rectangle 課題集約 {
  Object 課題 {
    課題内容
    進捗ステータス
    課題カテゴリ
  }

  Object 課題カテゴリ {
    課題カテゴリ名
  }

}

rectangle 課題の進捗集約 {
 Object 課題の進捗 {
    課題
    参加者
    進捗ステータス名
  }

  Object 進捗ステータス名 {
    進捗ステータス名
  }
}

チーム ||--o{ ペア
ペア ||--o{ 参加者
参加者 }|--|| 在籍ステータス
課題 }|--|| 課題の進捗
課題 }o--|| 課題カテゴリ
参加者 ||--|{ 課題の進捗
課題の進捗 }o--|| 進捗ステータス名



note bottom of 在籍ステータス
・「在籍中」「休会中」「退会済」が存在する。
・デフォルト値は「在籍中」
endnote

note top of 課題
・課題は全員共通
endnote

note top of 課題の進捗
・進捗ステータスは「未着手、レビュー待ち、完了」いずれかの値を持つ
・進捗ステータスはいつでも変更可能
・進捗ステータスを変更できるのは、課題の所有者だけ
endnote
@enduml
